### PR TITLE
Fixed typos-created pull-request becusae I have a question!

### PR DESCRIPTION
**Pull request by hupp2it**
I fixed a bunch of typos (sagebush, speices, veihcle, etc.), but I'm generally confused about why it looks like I made tons of changes. Would this be resolved if I added more things to git.ignore?

### CODE REVIEW

**Comment by wright13** [comment]
I've had this happen recently. All those extra files get created temporarily when you knit the .Rmd file, but for some reason they occasionally stick around. I noticed it happening after I updated RStudio. Try knitting again; they should go away and git will show them as deleted. At that point you can just make a commit and push to github and it should be fine. It's probably worth adding the reporting-dashboard-grba_files folder to .gitignore just to avoid future hassle.

**Comment by wright13** [comment]
Oh also when you commit, you can check the box that says "amend previous commit" and that way those files won't even show up in the commit history.

**Comment by hupp2it** [comment]
Using your advice, @wright13,  I amended the commit, and removed all the unnecessary changes to files!

**Comment by wright13** [comment]
Hey @hupp2it, I think you may have forgotten to push your last commit - I'm still seeing the temporary files.

**Comment by hupp2it** [comment]
Resolved in person!

**Pull request closed without merging**
